# Official VerneMQ Docker Image
# FROM erlio/docker-vernemq@sha256:4120060c98100b2507f02dc4381d4ae19c3435b6ff8ffceb9285579d62df3958
FROM erlio/docker-vernemq:1.6.2-2-gbea60e3

# Add Custom Config File
ADD vernemq.custom.1.6.2.conf /etc/vernemq/vernemq.conf
