apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: vernemq
  name: vernemq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vernemq
    spec:
      containers:
      - image: waveim/vernemq:latest
        name: wave-vernemq
        ports:
        - containerPort: 1883
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
