apiVersion: v1
kind: Service
metadata:
  labels:
    app: wave-manager
  name: wave-manager
spec:
  ports:
  - name: "8085"
    port: 8085
    targetPort: 8085
  selector:
    app: wave-manager
  type: LoadBalancer
status:
  loadBalancer: {}
