version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: hermes-rabbit
    container_name: hermes_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=example

  mongo:
    image: mongo:4
    restart: always
    container_name: hermes_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: hermes_mongoexpress
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis-cache:
    image: redis:4
    container_name: hermes_redis-cache
    restart: always
    ports:
      - "6379:6379"
    restart: always

  redis-heartbeat:
    image: redis:4
    container_name: hermes_redis-realtime
    restart: always
    ports:
      - "6380:6379"
    restart: always
